# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0b2af79fb207c6060422c73f20fe3067e993d67ca9ef58049c8d03c663db4818d25f36c5545ae24e7ddd08a3d27b662631e53d93fbc6a5946385ecf6e36c2bf

test:
  secret_key_base: 92104869b98ac5ff0b8d9d3f40ed71fd132da69587e115a91c749149b37311ca60e6d40bfca48cbf4a098a0ca08bf1f6fd524b751baafde36c355119f5b6e6e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
